services:
  - type: web
    name: incident-report-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node incident_server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true 